language: generic
sudo: required
services:
        - docker

before_install:
        - docker image build -t freeflychi/ops-web-demo:test -f Dockerfile.dev .

script:
  - docker run -e CI=true freeflychi/ops-web-demo:test npm run test -- --coverage
  
